version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=names
        ports:
            - '3307:3306'
        volumes:
            - db:/var/lib/mysql
    app:
        depends_on:
            - mysqldb
        build:
            context: .
            dockerfile: Dockerfile
        restart: on-failure
        ports:
            - '8080:8080'
        environment:
            SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/names?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
        volumes:
            - .m2:/root/.m2
        stdin_open: true
        tty: true

volumes:
    db:
